#pragma once

#include <EngineRuntime.h>

namespace Engine
{
	namespace XX
	{
		ENGINE_REFLECTED_CLASS(Plugin, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Name);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Target);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, File);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(InstalledProduct, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Identifier);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Version);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Platform);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, PackageType);
			ENGINE_DEFINE_REFLECTED_PROPERTY(STRING, Path);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, CreatedLinks);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, CreatedRegistryKeys);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, CreatedRegistryValues);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, CreatedPathEntries);
			ENGINE_DEFINE_REFLECTED_ARRAY(STRING, PermanentFiles);
			ENGINE_DEFINE_REFLECTED_GENERIC_ARRAY(Plugin, Plugins);
		ENGINE_END_REFLECTED_CLASS
		ENGINE_REFLECTED_CLASS(InstallationDatabase, Engine::Reflection::Reflected)
			ENGINE_DEFINE_REFLECTED_GENERIC_ARRAY(InstalledProduct, Products);
		ENGINE_END_REFLECTED_CLASS
	}
}